package com.example.devaudioreccordings.ui.theme.tealScheme
import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF006B5E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF22A895)
val onPrimaryContainerLight = Color(0xFF00362E)
val secondaryLight = Color(0xFF3D665E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFBFECE1)
val onSecondaryContainerLight = Color(0xFF436C64)
val tertiaryLight = Color(0xFF6B509D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFA588DA)
val onTertiaryContainerLight = Color(0xFF3A1D6A)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF5FBF8)
val onBackgroundLight = Color(0xFF171D1B)
val surfaceLight = Color(0xFFF5FBF8)
val onSurfaceLight = Color(0xFF171D1B)
val surfaceVariantLight = Color(0xFFD8E6E1)
val onSurfaceVariantLight = Color(0xFF3D4946)
val outlineLight = Color(0xFF6D7A76)
val outlineVariantLight = Color(0xFFBCC9C5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C3230)
val inverseOnSurfaceLight = Color(0xFFECF2EF)
val inversePrimaryLight = Color(0xFF63DAC5)
val surfaceDimLight = Color(0xFFD6DBD8)
val surfaceBrightLight = Color(0xFFF5FBF8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F2)
val surfaceContainerLight = Color(0xFFE9EFEC)
val surfaceContainerHighLight = Color(0xFFE4E9E6)
val surfaceContainerHighestLight = Color(0xFFDEE4E1)

val primaryLightMediumContrast = Color(0xFF003E36)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF007B6C)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF113D36)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF4C756C)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF412671)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF7A5FAD)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF5FBF8)
val onBackgroundLightMediumContrast = Color(0xFF171D1B)
val surfaceLightMediumContrast = Color(0xFFF5FBF8)
val onSurfaceLightMediumContrast = Color(0xFF0D1211)
val surfaceVariantLightMediumContrast = Color(0xFFD8E6E1)
val onSurfaceVariantLightMediumContrast = Color(0xFF2C3936)
val outlineLightMediumContrast = Color(0xFF485552)
val outlineVariantLightMediumContrast = Color(0xFF63706C)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2C3230)
val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2EF)
val inversePrimaryLightMediumContrast = Color(0xFF63DAC5)
val surfaceDimLightMediumContrast = Color(0xFFC2C8C5)
val surfaceBrightLightMediumContrast = Color(0xFFF5FBF8)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEFF5F2)
val surfaceContainerLightMediumContrast = Color(0xFFE4E9E6)
val surfaceContainerHighLightMediumContrast = Color(0xFFD8DEDB)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCDD3D0)

val primaryLightHighContrast = Color(0xFF00332C)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF005348)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF04322C)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF275049)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF371A67)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF553A86)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF5FBF8)
val onBackgroundLightHighContrast = Color(0xFF171D1B)
val surfaceLightHighContrast = Color(0xFFF5FBF8)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFD8E6E1)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF222F2C)
val outlineVariantLightHighContrast = Color(0xFF3F4C49)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2C3230)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF63DAC5)
val surfaceDimLightHighContrast = Color(0xFFB4BAB7)
val surfaceBrightLightHighContrast = Color(0xFFF5FBF8)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFECF2EF)
val surfaceContainerLightHighContrast = Color(0xFFDEE4E1)
val surfaceContainerHighLightHighContrast = Color(0xFFD0D6D3)
val surfaceContainerHighestLightHighContrast = Color(0xFFC2C8C5)

val primaryDark = Color(0xFF63DAC5)
val onPrimaryDark = Color(0xFF003730)
val primaryContainerDark = Color(0xFF22A895)
val onPrimaryContainerDark = Color(0xFF00362E)
val secondaryDark = Color(0xFFA4CFC5)
val onSecondaryDark = Color(0xFF093730)
val secondaryContainerDark = Color(0xFF275048)
val onSecondaryContainerDark = Color(0xFF96C1B7)
val tertiaryDark = Color(0xFFD4BBFF)
val onTertiaryDark = Color(0xFF3B1F6B)
val tertiaryContainerDark = Color(0xFFA588DA)
val onTertiaryContainerDark = Color(0xFF3A1D6A)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1513)
val onBackgroundDark = Color(0xFFDEE4E1)
val surfaceDark = Color(0xFF0F1513)
val onSurfaceDark = Color(0xFFDEE4E1)
val surfaceVariantDark = Color(0xFF3D4946)
val onSurfaceVariantDark = Color(0xFFBCC9C5)
val outlineDark = Color(0xFF869490)
val outlineVariantDark = Color(0xFF3D4946)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4E1)
val inverseOnSurfaceDark = Color(0xFF2C3230)
val inversePrimaryDark = Color(0xFF006B5E)
val surfaceDimDark = Color(0xFF0F1513)
val surfaceBrightDark = Color(0xFF343A39)
val surfaceContainerLowestDark = Color(0xFF0A0F0E)
val surfaceContainerLowDark = Color(0xFF171D1B)
val surfaceContainerDark = Color(0xFF1B211F)
val surfaceContainerHighDark = Color(0xFF252B2A)
val surfaceContainerHighestDark = Color(0xFF303634)

val primaryDarkMediumContrast = Color(0xFF7AF0DB)
val onPrimaryDarkMediumContrast = Color(0xFF002B25)
val primaryContainerDarkMediumContrast = Color(0xFF22A895)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000101)
val secondaryDarkMediumContrast = Color(0xFFB9E5DB)
val onSecondaryDarkMediumContrast = Color(0xFF002B25)
val secondaryContainerDarkMediumContrast = Color(0xFF6F9990)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFE6D5FF)
val onTertiaryDarkMediumContrast = Color(0xFF301260)
val tertiaryContainerDarkMediumContrast = Color(0xFFA588DA)
val onTertiaryContainerDarkMediumContrast = Color(0xFF03000E)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0F1513)
val onBackgroundDarkMediumContrast = Color(0xFFDEE4E1)
val surfaceDarkMediumContrast = Color(0xFF0F1513)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF3D4946)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD2DFDB)
val outlineDarkMediumContrast = Color(0xFFA7B5B1)
val outlineVariantDarkMediumContrast = Color(0xFF86938F)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDEE4E1)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2A)
val inversePrimaryDarkMediumContrast = Color(0xFF005247)
val surfaceDimDarkMediumContrast = Color(0xFF0F1513)
val surfaceBrightDarkMediumContrast = Color(0xFF404644)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF040807)
val surfaceContainerLowDarkMediumContrast = Color(0xFF191F1D)
val surfaceContainerDarkMediumContrast = Color(0xFF232927)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2E3432)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF393F3D)

val primaryDarkHighContrast = Color(0xFFB0FFEE)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF5ED6C1)
val onPrimaryContainerDarkHighContrast = Color(0xFF000E0B)
val secondaryDarkHighContrast = Color(0xFFCDF9EE)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFA0CBC1)
val onSecondaryContainerDarkHighContrast = Color(0xFF000E0B)
val tertiaryDarkHighContrast = Color(0xFFF6ECFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFD1B6FF)
val onTertiaryContainerDarkHighContrast = Color(0xFF120030)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF0F1513)
val onBackgroundDarkHighContrast = Color(0xFFDEE4E1)
val surfaceDarkHighContrast = Color(0xFF0F1513)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3D4946)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE5F3EE)
val outlineVariantDarkHighContrast = Color(0xFFB8C6C1)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDEE4E1)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF005247)
val surfaceDimDarkHighContrast = Color(0xFF0F1513)
val surfaceBrightDarkHighContrast = Color(0xFF4B514F)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1B211F)
val surfaceContainerDarkHighContrast = Color(0xFF2C3230)
val surfaceContainerHighDarkHighContrast = Color(0xFF373D3B)
val surfaceContainerHighestDarkHighContrast = Color(0xFF424846)














